config/routes.rb
Todo::Application.routes.draw do

  devise_for :users

  get "landing_pages/home"
  get "assignments/complete"

  root :to => 'landing_pages#home'

  resources :users
  resources :assignments
  resources :events

end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id         :integer          not null, primary key
#  class_name :string(255)
#  homework   :string(255)
#  due_date   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  completed  :boolean
#

class Assignment < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :class_name, :homework, :due_date, :user_id, :completed

  validates :user, :class_name, :homework, :due_date, :presence => true 

  scope :incomplete, -> { where(completed: false).order(:homework)}
  scope :complete, -> { where(completed: true).order(:homework)}

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @assignments_complete = Assignment.complete.sort_by! { |m| m.due_date }
    @assignments_incomplete = Assignment.incomplete.sort_by! { |m| m.due_date }
  end

  def new
  	@assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(params[:assignment])
    @assignment.completed = false;
    if @assignment.save
      client = Postmark::ApiClient.new('2cb38ae3-d143-4150-9dca-cbe8939c1858')
      client.deliver(from: 'zhouwe@seas.upenn.edu',
               to: current_user.email,
               subject: 'New Assignment Creatation',
               html_body: "Hi #{current_user.email},<br><br>You just created a new assignment!
                          <p>Check it out on the app!<br><br>
                          Thanks, The Personal Planner App (http://kellysplanner.herokuapp.com/)")
		  redirect_to assignments_path
    else
		  render 'new'
    end
  end

  def edit 
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update_attributes(params[:assignment])
      redirect_to assignments_path
    else
      render 'edit'
    end
  end

  def complete
    @assignment = Assignment.find(params[:id])
    @assignment.completed = true;
    if @assignment.save
      redirect_to assignments_path
    else
      render 'edit'
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    client = Postmark::ApiClient.new('2cb38ae3-d143-4150-9dca-cbe8939c1858')
    client.deliver(from: 'zhouwe@seas.upenn.edu',
               to: current_user.email,
               subject: 'Deleted Assignment',
               html_body: "Hi #{current_user.email},<br><br>You just deleted an assignment.
                          <p>Check it out on the app!<br><br>
                          Thanks, The Personal Planner App (http://kellysplanner.herokuapp.com/)")
    @assignment.destroy
    redirect_to assignments_path
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<div class="formtastic-form">
<%= semantic_form_for @assignment do |f| %>
  <%= f.semantic_errors %>  
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :class_name, :input_html => {:id => "form-input" } %>
  <%= f.input :homework, :input_html => {:id => "form-input2" } %>
  <%= f.input :due_date, :input_html => {:id => "datepicker" } %>
  <!--%= f.hidden_field :completed, :input_html => { :value => "false" }  %-->
  <%= f.action :submit %>
<% end %>

</div>

app/views/assignments/edit.html.erb
<h1 id="title">Edit Assignment</h1>

<div class="formtastic-form">
<%= semantic_form_for @assignment do |f| %>
  <%= f.semantic_errors %>  
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :class_name, :input_html => {:id => "form-input" } %>
  <%= f.input :homework, :input_html => {:id => "form-input2" } %>
  <%= f.input :due_date, :input_html => {:id => "datepicker" } %>
  <%= f.input :completed %>
  <%= f.action :submit %>
<% end %>

</div>

app/views/assignments/index.html.erb
<h1 id="title">Assignments List</h1>
<br>
<h3><span class="glyphicon glyphicon-remove"></span> Incomplete Assignments</h3>
<table class="table table-hover">
 <thead>
 	<tr>
 		<td>Class</td>
 		<td>Assignment</td>
 		<td>Due Date</td>
 		<td>Completed?</td>
 		<td>Action</td>
 	</tr>
 </thead>
 <tbody>
 	<% @assignments_incomplete.each do |assig| %>
 	<% if assig.user == current_user %>
 	<tr>
 		<td><%= assig.class_name %></td>
 		<td><%= assig.homework %></td>
 		<td><%= assig.due_date %></td>
 		<td><%= link_to "Done!", "/assignments/complete?id=#{assig.id}", html_options = {:class => "btn btn-success"}%></td>
 		<td><!%= link_to "Edit", edit_assignment_path(assig.id) %> 
 		<%= link_to 'Edit', edit_assignment_path(assig.id),:class => 'btn btn-mini btn-warning'%>
 		<!%= link_to "Delete", assig, method: :delete %>
 		<%= link_to 'Delete', assignment_path(assig), :confirm => "Are you sure you want to delete this document?", :method => :delete, :class => 'btn btn-mini btn-danger'%></td>
 	</tr>
 	<% end %>
 	<% end %>
 </tbody>
</table>

<br>
<h3><span class="glyphicon glyphicon-ok"></span> Completed Assignments</h3>
<table class="table table-hover">
 <thead>
 	<tr>
 		<td>Class</td>
 		<td>Assignment</td>
 		<td>Due Date</td>
 		<td>Action</td>
 	</tr>
 </thead>
 <tbody>
 	<% @assignments_complete.each do |assig| %>
 	<% if assig.user == current_user %>
 	<tr>
 		<td><%= assig.class_name %></td>
 		<td><%= assig.homework %></td>
 		<td><%= assig.due_date %></td>
 		<td><!%= link_to "Edit", edit_assignment_path(assig.id) %> 
 		<%= link_to 'Edit', edit_assignment_path(assig.id),:class => 'btn btn-mini btn-warning'%>
 		<!%= link_to "Delete", assig, method: :delete %>
 		<%= link_to 'Delete', assignment_path(assig), :confirm => "Are you sure you want to delete this document?", :method => :delete, :class => 'btn btn-mini btn-danger'%></td>
 	</tr>
 	<% end %>
 	<% end %>
 </tbody>
</table>

<br/>
<%= link_to "New Assignment", new_assignment_path, html_options = {:class => "btn btn-info"} %>

app/views/assignments/new.html.erb
<h1 id="title">New Assignment</h1>

<%= render :partial => 'form' %>

app/views/assignments/show.html.erb
<h3>
Class Name: <%= @assignment.class_name %><br/>
Homework: <%= @assignment.homework %><br/>
Due Date: <%= @assignment.due_date %><br/>
User: <%= @assignment.user.name %><br/>
</h3>