config/routes.rb
Todo::Application.routes.draw do

  devise_for :users

  get "landing_pages/home"
  get "assignments/complete"

  root :to => 'landing_pages#home'

  resources :users
  resources :assignments
  resources :events

end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
    @assignments_incomplete = Assignment.incomplete.sort_by! { |m| m.due_date }
    @count = 0
  	def resource_name
    	:user
  	end
 
  	def resource
    	@resource ||= User.new
  	end
 
  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end

  end


end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/home.html.erb
<html>
<head> 
	<title>To-Do List</title> 
</head>

<div class="row">

  <div class="col-md-7">
  	<h3> <span class="glyphicon glyphicon-home"></span> Personal Planner </h3>
	<br/><br/>
	<img src="http://25.media.tumblr.com/tumblr_lt4bdjf6EM1qbymhco1_500.gif"/>
  </div>

  <div class="col-md-5">
  	<br/><br/><br/>
  	<div class="box">

  	<% if !user_signed_in? %>
    <h2><u>Login</u></h2>
  	<%= form_for(@resource, :as => :user, :url => session_path(:user), :html => {:class => "form"}) do |f| %>
  	<div><%= f.label :email %><br />
  	<%= f.email_field :email, :autofocus => true %></div>
  	<div><%= f.label :password %><br />
  	<%= f.password_field :password %></div>

  	<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>

  	<div><%= f.submit "Sign in", :class => "btn btn-primary" %></div>
	<% end %>
	<p>Not a user? <%= link_to 'Sign Up', new_user_registration_path%>
	<% else %>

	<h2>Welcome, <%=current_user.email%>! </h2><br/>

  <h4><u> Incomplete Assignments </u></h4>
  
    <% @assignments_incomplete.each do |assig| %>
    <% if assig.user == current_user %>
      <%= "#{assig.class_name} - #{assig.homework} (Due: #{assig.due_date})" %><br/>
      <% @count = @count + 1 %>
    <% end %>
    <% end %>

  <% if @count == 0 %>
  All assignments completed! Yay freedom!<br/>
  <% end %>
  
  <br/><%= link_to "List of assignments",assignments_path, :class=>"btn btn-info" %>
  <br/><br/><h4><u>Events</u></h4>
  <%= link_to "List of events",events_path, :class=>"btn btn-info" %>

	<% end %>
	</div>

  </div>

</div>
	
</html>