config/routes.rb
Todo::Application.routes.draw do

  devise_for :users

  get "landing_pages/home"
  get "assignments/complete"

  root :to => 'landing_pages#home'

  resources :users
  resources :assignments
  resources :events

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  date        :string(255)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :string(255)
#

class Event < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :title, :user_id, :description

  validates :user, :title, :date, :presence => true

  scope :meeting, -> { where('title = ?', "Meeting")}
  scope :date, -> { where('title = ?', "Date")}
  scope :others, lambda { {:conditions => ['title != ? AND title != ?', "Meeting", "Date"]} }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @events = Event.all.sort_by! { |m| m.date }
    @events_meetings = Event.meeting.sort_by! { |m| m.date }
    @events_dates = Event.date.sort_by! { |m| m.date }
    @events_others = Event.others.sort_by! { |m| m.date }
  end

  def new
  	@event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      client = Postmark::ApiClient.new('2cb38ae3-d143-4150-9dca-cbe8939c1858')
      client.deliver(from: 'zhouwe@seas.upenn.edu',
               to: current_user.email,
               subject: 'New Event Creatation',
               html_body: "Hi #{current_user.email},<br><br>You just created a new event!
                          <p>Check it out on the app!<br><br>
                          Thanks, The Personal Planner App (http://kellysplanner.herokuapp.com/)")

		  redirect_to events_path
    else
		  render 'new'
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    client = Postmark::ApiClient.new('2cb38ae3-d143-4150-9dca-cbe8939c1858')
    client.deliver(from: 'zhouwe@seas.upenn.edu',
               to: current_user.email,
               subject: 'Deleted Event',
               html_body: "Hi #{current_user.email},<br><br>You just deleted an event.
                          <p>Check it out on the app!<br><br>
                          Thanks, The Personal Planner App (http://kellysplanner.herokuapp.com/)")

    @event.destroy
    redirect_to events_path
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="formtastic-form">
<%= semantic_form_for @event, :html => { :class => "formtastic-form"} do |f| %>
  <%= f.semantic_errors %>  
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <!%= f.input :title %>
  <%= f.label :title %><br/>
    <%= f.select(:title, options_for_select([['Meeting', 'Meeting'], ['Date', 'Date'], ['Other', 'Other']], 3), {}, { :class => 'select' }) %> <br/>
  <%= f.input :description %>
  <%= f.input :date, :input_html => {:id => "datepicker" } %>

  <%= f.action :submit, :input_html => {:class => "btn btn-info" }  %>

<% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<h1>Events List</h1>

<br>
<h3><span class="glyphicon glyphicon-list"></span> Meetings</h3>
<table class="table table-hover">
 <thead>
 	<tr>
 		<td>Title</td>
 		<td>Description</td>
 		<td>Date</td>
 		<td>Action</td>
 	</tr>
 </thead>
 <tbody>
 	<% @events_meetings.each do |event| %>
 	<% if event.user == current_user %>
 	<tr>
 		<td><%= event.title %></td>
 		<td><%= event.description %></td>
 		<td><%= event.date %></td>
 		<td><!%= link_to "Edit", edit_event_path(event.id) %> <!%= link_to "Delete", event, method: :delete %>
 		<%= link_to 'Edit', edit_event_path(event.id),:class => 'btn btn-mini btn-warning'%>
 		<%= link_to 'Delete', event_path(event), :confirm => "Are you sure you want to delete this document?", :method => :delete, :class => 'btn btn-mini btn-danger'%></td>

 	</tr>
 	<% end %>
 	<% end %>
 <tbody>
</table>

<br>
<h3><span class="glyphicon glyphicon-heart"></span> Dates</h3>
<table class="table table-hover">
 <thead>
 	<tr>
 		<td>Title</td>
 		<td>Description</td>
 		<td>Date</td>
 		<td>Action</td>
 	</tr>
 </thead>
 <tbody>
 	<% @events_dates.each do |event| %>
 	<% if event.user == current_user %>
 	<tr>
 		<td><%= event.title %></td>
 		<td><%= event.description %></td>
 		<td><%= event.date %></td>
 		<td><!%= link_to "Edit", edit_event_path(event.id) %> <!%= link_to "Delete", event, method: :delete %>
 		<%= link_to 'Edit', edit_event_path(event.id),:class => 'btn btn-mini btn-warning'%>
 		<%= link_to 'Delete', event_path(event), :confirm => "Are you sure you want to delete this document?", :method => :delete, :class => 'btn btn-mini btn-danger'%></td>

 	</tr>
 	<% end %>
 	<% end %>
 <tbody>
</table>


<br>
<h3><span class="glyphicon glyphicon-unchecked"></span> Others</h3>
<table class="table table-hover">
 <thead>
 	<tr>
 		<td>Title</td>
 		<td>Description</td>
 		<td>Date</td>
 		<td>Action</td>
 	</tr>
 </thead>
 <tbody>
 	<% @events_others.each do |event| %>
 	<% if event.user == current_user %>
 	<tr>
 		<td><%= event.title %></td>
 		<td><%= event.description %></td>
 		<td><%= event.date %></td>
 		<td><!%= link_to "Edit", edit_event_path(event.id) %> <!%= link_to "Delete", event, method: :delete %>
 		<%= link_to 'Edit', edit_event_path(event.id),:class => 'btn btn-mini btn-warning'%>
 		<%= link_to 'Delete', event_path(event), :confirm => "Are you sure you want to delete this document?", :method => :delete, :class => 'btn btn-mini btn-danger'%></td>

 	</tr>
 	<% end %>
 	<% end %>
 <tbody>
</table>

<br/>
<%= link_to "New Event", new_event_path, html_options = {:class => "btn btn-info"} %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<h3>
Meeting Title: <%= @event.title %><br/>
Due Date: <%= @event.date %><br/>
User: <%= @event.user.name %><br/>
</h3>