config/routes.rb
Todo::Application.routes.draw do

  devise_for :users

  get "landing_pages/home"
  get "assignments/complete"

  root :to => 'landing_pages#home'

  resources :users
  resources :assignments
  resources :events

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Personal Planner</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Personal Planner</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Assignments", assignments_path %></li>
            <li><%= link_to "Events", events_path %></li>
            <!-- NEED TO FIX -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Assignment", new_assignment_path %></li>
                <li class="divider"></li>
                <li><%= link_to "New Event", new_event_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<!center>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
  <% if notice %>
  <p class="notice alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </div>
  <div class="col-md-1"></div>
</div>

<!/center>

<script>
  $('.dropdown-toggle').dropdown();
</script>

</body>
</html>